#!/usr/bin/env python3
from math import pi
from rosgraph import ROS_HOSTNAME
import rospy
import sys
import threading
import hello_helpers.hello_misc as hm
from std_msgs.msg import Float64, Bool
from std_srvs.srv import Trigger
from sensor_msgs.msg import JointState
from stretch_moveit_shim.msg import Joint, Joints
from stretch_moveit_shim.srv import SetBody, SetBodyRequest, SetBodyResponse, GetBody,  GetBodyRequest, GetBodyResponse, SetJoints, SetJointsRequest, SetJointsResponse


class StretchInterface(hm.HelloNode):
    def __init__(self):
        hm.HelloNode.__init__(self)
        self.joint_states = None
        self.joint_states_lock = threading.Lock()
        self.letter_height_m = 0.2
        hm.HelloNode.main(self, 'stretch_interface',
                          'stretch_interface', wait_for_first_pointcloud=False)

        # Check if robot is calibrated
        msg = rospy.wait_for_message("/is_calibrated", Bool)
        if (msg.data == False):
            home = rospy.ServiceProxy("/calibrate_the_robot", Trigger)
            home()
        # Stow robot
        self.stow_robot()
        # Switch robot to navigation mode
        navigation = rospy.ServiceProxy("/switch_to_navigation_mode", Trigger)
        navigation()

        self.set_pose_service = rospy.Service(
            '/stretch_interface/set_joints', SetJoints, self.set_joints)
        self.get_pose_service = rospy.Service(
            '/stretch_interface/get_joints', GetBody, self.get_pose)
        
        self.set_joints_sub = rospy.Subscriber('/stretch_interface/set_joints', Joints, self.set_joints_callback)

    def get_pose(self, req):
        pose = GetBodyResponse()
        pose.joint_head_pan = self.joint_states['joint_head_pan']
        pose.joint_head_tilt = self.joint_states['joint_head_tilt']
        pose.joint_lift = self.joint_states['joint_lift']
        pose.wrist_extension = self.joint_states['wrist_extension']
        pose.joint_wrist_roll = self.joint_states['joint_wrist_roll']
        pose.joint_wrist_pitch = self.joint_states['joint_wrist_pitch']
        pose.joint_wrist_yaw = self.joint_states['joint_wrist_yaw']
        pose.gripper_aperture = self.joint_states['gripper_aperture']
        return pose

    def set_joints(self, req: SetJointsRequest):
        pose = {}
        for msg in req.joints:
            pose[msg.joint_name] = msg.val
            self.joint_states[msg.joint_name] = msg.val
        self.move_to_pose(pose)
        return SetJointsResponse()
    
    def set_joints_callback(self, msg: Joints):
        pose = {}
        for msg in msg.joints:
            pose[msg.joint_name] = msg.val
            self.joint_states[msg.joint_name] = msg.val
        self.move_to_pose(pose, return_before_done=True)
        return

    def stow_robot(self):
        pose = {'joint_head_pan': 0,
                'joint_head_tilt': 0,
                'joint_lift': 0.2,
                'wrist_extension': 0,
                'joint_wrist_roll': 0,
                'joint_wrist_pitch': 0,
                'joint_wrist_yaw': pi,
                'gripper_aperture': 0}
        self.joint_states = pose
        self.move_to_pose(pose)


if __name__ == '__main__':
    # rospy.init_node('stretch_interface', log_level=rospy.DEBUG)
    node = StretchInterface()
    rospy.sleep(1)
    rospy.loginfo('Ready')
    rospy.spin()
